Clarifying some steps
scipion-em/docs pull request #52
Opened 2022-07-07 12:11 UTC by albertmena

2022-07-28 15:53 UTC, pconesa commented on docs/developer/tutorials/creating-streaming-protocol.rst
> +                    # use _insertFunctionStep with registerImageStepadding the parameter file, and
there is a missing space?

2022-07-28 15:54 UTC, pconesa requested changes
Thank you so much for reviewing and updating the documentation!

2022-08-31 12:59 UTC, albertmena commented on docs/developer/tutorials/creating-streaming-protocol.rst
> +                    # use _insertFunctionStep with registerImageStepadding the parameter file, and
y e s

2022-09-06 13:45 UTC, pconesa approved these changes
Nice!

2022-09-06 13:45 UTC, merged